### ISSUE TITLE
Valores recomendados de mediciones

### ISSUE THREAD

**Issue by javifly** [UlisesGascon/Calidad-del-Aire#1]
Hola,

Queria construir este dispositivo para recoger los datos de mi pueblo y subirlos al ordenador.
¿Podrias indicarme cuales son los valores recomendados para cada una de las variables?
Es decir para una calidad de aire buena entre que rango debe estar cada uno de esos valores: Amonico, Alcohol, metano... etc...

Gracias

**Comment by UlisesGascon** [comment]
Pues... justo ese es un problema bastante extendido. Es dificil saber el umbral de trabajo en cada municipio, porque en muchas ocasiones es necesario tener varias lecturas a lo largo de un día para saber si sobrepasamos el límite. Yo por ahora estoy usando la propia resistencia con valores "aleatorios (pero altos)"
