### ISSUE TITLE
en el cod no lees los 9 sensores que tienes en la caja

### ISSUE THREAD

**Issue by javifly** [UlisesGascon/Calidad-del-Aire#3]
No se si me equivoco pero en tu archivo de codigo no veo que leas mas que 7 sensores mientras que en la caja tienes 9. ¿Como puede ser eso?

¿Por otro lado la fuente de 5V 3A está medida bien?¿O sirve con una de 2A?

Saludos, gracias

**Comment by javifly** [comment]
No lees el MQ-5 ni el MQ-9 ¿por que?

**Comment by UlisesGascon** [comment]
Hola @javifly. Creo recordar que los sensores MQ-5 y MQ-9 median datos similares a otros sensores ya incluidos en la caja y para simplificar la lectura decidí omitirlos del JSON resultante, pero estan instalados y se pueden utilizar. La fuente de alimentación que uso es una reciclada, pero creo que con 2A también debería de funcionar. En [las especificaciones](https://github.com/UlisesGascon/Calidad-del-Aire/tree/master/datasheets) tienes los consumos relativos.

**Comment by javifly** [comment]
ok, si con un de 2A debería ser suficiente según mis cálculos si...

Según he visto los sensores son:
// MQ-2 / GasLicuadoDelPetroleo / glp // ppm (<1 ppm) (60% C3H8 y 40% C4H10)
// MQ-3 / Alcohol / alcohol // ppm (¿¿¿<1 ppm???) (C2H6O)
// MQ-4 / Metano / metano // ppm (<1.5 ppm) (CH4)
// MQ-5 / Gas natural / gnatural // ¿nose1?
// MQ-6 / Propano / propano // ppm (<1 ppm) (C3H8)
// MQ-7 / MonoxidoDeCarbono / monoxidoDeCarbono // ppm (<1 ppm) (CO)
// MQ-8 / Hidrogeno / hidrogeno // ppm (<0.5 ppm) (H)
// MQ-9 / Monóxido de carbono / moncarb // ¿nose2?
 // MQ-135 / DioxidoDeCarbono / dioxidoDeCarbono // ppm (310-330 ppm) (CO2)
 // MQ-135 / OxidosDeNitrogeno / oxidosDeNitrogeno // ppm (0.001-0.01 ppm) (NO)
 // MQ-135 / Amoniaco / amoniaco // ppm (<0.015 ppm) (NH3)

Vamos que creo que miden:
MQ-5 Sensor de Gas Propano
MQ-9 Sensor de Gas Monóxido de Carbono 

Y ningún otro sensor miden lo que MQ5 y MQ9, ¿no?

¿Me ayudarias con la recopilacion de datos de estos 2 sensores?

**Comment by javifly** [comment]
Efectivamente MQ7 y MQ9 miden lo mismo.
Pero que mida lo mismo que MQ5 no veo...

**Comment by AnizCoronel** [comment]
¿Tienes algún diagrama de conexión del sistema completo?
¿O puedes mostrar la conexión de la fuente de poder con los sensores y el arduino?

**Comment by UlisesGascon** [comment]
[Este](https://github.com/UlisesGascon/Calidad-del-Aire#conexiones) es el mejor esquema de conexiones que tengo, puedes usar la foto como guía ;-)
