### ISSUE TITLE
Duda presupuestaria

### ISSUE THREAD

**Issue by Punksolid** [UlisesGascon/Calidad-del-Aire#4]
Hola, ando desarrollando un frontend para la interpretación de datos de la calidad del aire y estaba considerando talvez en hacer un dispositivo. 
Cuanto invertiste aproximadamente en el proyecto?
Qué desventaja tiene tu dispositivo comparado con los productos comerciales que están a la venta?

Saludos y felicidades por la documentación.

**Comment by UlisesGascon** [comment]
Hola @Punksolid !

En su momento creo que me costo entorno a los 50-100€ entre materiales, sensores, alquiler de corte laser, etc... y todas las pruebas que fui sacando hasta que di con la versión final.

Creo que algunos productos comerciales ya tienen sensores más afinados y específicos aunque son mucho menos DYI. :-)
